# -*- coding: utf-8 -*-
"""Diagonal_Difference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYgSJls9C4pt2e6O7-97hmhw1rQA10_p
"""

def diff(arr, n):
 
    sum1 = 0
    sum2 = 0
 
    for i in range(0, n):
        for j in range(0, n):
         
            if (i == j):
                d1 += arr[i][j]
 
            if (i == n - j - 1):
                d2 += arr[i][j]
         
    return abs(d1 - d2);
 
n = 3
 
arr = [[1, 2, 3],
       [4 , 5, 6],
       [7, 9, 5]]
 
print(difference(arr, n))

