# -*- coding: utf-8 -*-
"""Lonely Integer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DvOAVh4SaP7wfvt1upPOVJ1-fF0i8ki9

Given an array of integers, where all elements but one occur twice, find the unique element.
"""

def singleNum(ar):
  
  length=len(ar)
  r=ar[0]
  for i in range(1,length):
    r=r^ar[i]
  print(r)

ar=[1,2,3,4,3,2,1]
singleNum(ar)

