# -*- coding: utf-8 -*-
"""Mini-Max Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4rjFwM0xs5TfX0nrpV6tNr_43eLRoe3

Given five positive integers, find the minimum and maximum values that can be calculated by summing exactly four of the five integers. Then print the respective minimum and maximum values as a single line of two space-separated long integers.
"""

from array import*
minV=0
maxV=0
arr=[5,7,3,1,6]
arr.sort()

length=len(arr)
for i in range(length-1):
  minV+=min(arr[i],arr[i+1])
  maxV+=max(arr[i],arr[i+1])
print('Minimum and maximum values are',minV,"",maxV)