# -*- coding: utf-8 -*-
"""Time Conversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dPPD4doutliVz5xSDQf_mULiTZfM689f

Given a time in 12 -hour AM/PM format, convert it to military (24-hour) time.
"""

time = input("enter the time in hh:mm:ssAM/PM format")
length=len(time)

h1=ord(time[0])-ord('0')
h2=ord(time[1])-ord('0')
hh = h1*10+h2%10

if(time[8]=='A'):
  if(hh==12):
    print('00',end="")
    for i in range (2,8):
      print(time[i],end="")

  else:
    for i in range (0,8):
      print(time[i],end="")

elif(time[8]=='P'):
  if(hh==12):
    print('12',end="")
    for i in range(2,8):
      print(time[i],end="")
  else:
    hh+=12
    print(hh,end="")
    for i in range(2,8):
      print(time[i],end="")

: